name: Integration tests

on:
  pull_request:
  schedule:
  - cron: "0 15 * * SAT"

jobs:
  integration-tests-juju-3:
    uses: 
      canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      provider: lxd
      trivy-fs-enabled: false
      trivy-image-config: "trivy.yaml"
      self-hosted-runner: false
      self-hosted-runner-label: "edge"
      juju-channel: '3/stable'
      with-uv: true
      working-directory: dovecot-charm
      modules: |
        [
          "test_action.py",
          "test_config.py",
          "test_ha.py",
          "test_mail.py",
          "test_storage.py",
          "test_tls.py",
          "test_ha.py",
        ]
  allure-report:
    if: ${{ !cancelled() && github.event_name == 'schedule' }}
    needs:
    - integration-tests-juju-3
    uses: canonical/operator-workflows/.github/workflows/allure_report.yaml@main
