name: Integration tests

on:
  pull_request:
  schedule:
  - cron: "0 15 * * SAT"

jobs:
  integration-tests-juju-3:
    strategy:
      matrix:
        charm:
          - name: dovecot
            working-directory: ./dovecot-charm
            modules: |
              [
                "test_action.py",
                "test_config.py",
                "test_ha.py",
                "test_mail.py",
                "test_observability.py",
                "test_storage.py",
                "test_tls.py"
              ]
          - name: opendkim-operator
            working-directory: ./opendkim-operator
            modules: '["test_charm.py"]'
            pre-run-script: ./opendkim-operator/tests/integration/setup-integration-tests.sh
          - name: postfix-relay-operator
            working-directory: ./postfix-relay-operator
            modules: '["test_charm.py"]'
            pre-run-script: ./postfix-relay-operator/tests/integration/mailcatcher-installation.sh
    name: Integration tests for ${{ matrix.charm.name }}
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      extra-arguments: '-x --log-format="%(asctime)s %(levelname)s %(message)s"'
      provider: lxd
      trivy-fs-enabled: false
      juju-channel: 3/stable
      self-hosted-runner: true
      self-hosted-runner-label: "self-hosted-linux-amd64-noble-large"
      charmcraft-channel: latest/edge
      working-directory: ${{ matrix.charm.working-directory }}
      modules: ${{ matrix.charm.modules }}
      pre-run-script: ${{ matrix.charm.pre-run-script }}
      with-uv: true
  integration-tests-global:
    uses:
      canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      use-canonical-k8s: true
      provider: lxd
      self-hosted-runner: true
      self-hosted-runner-label: "self-hosted-linux-amd64-noble-large"
      juju-channel: 3/stable
      modules: |
        [
          "test_whole_email_system.py"
        ]
      with-uv: true
      pre-run-script: ./tests/integration/setup-integration-tests.sh
  allure-report:
    if: ${{ !cancelled() && github.event_name == 'schedule' }}
    needs:
    - integration-tests-juju-3
    - integration-tests-global
    uses: canonical/operator-workflows/.github/workflows/allure_report.yaml@main
