name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish-to-edge:
    strategy:
      matrix:
        configuration:
          [
            {
              working-directory: "./dovecot-charm",
              channel: "2.3/edge",
              tag-prefix: "dovecot",
            },
            {
              working-directory: "./opendkim-operator",
              channel: "2/edge",
              tag-prefix: "opendkim-operator",
            },
            {
              working-directory: "./postfix-relay-operator",
              channel: "3/edge",
              tag-prefix: "postfix-relay",
            },
            {
              working-directory: "./postfix-relay-configurator-operator",
              channel: "3/edge",
              tag-prefix: "postfix-relay-configurator",
            },
          ]
    permissions:
      actions: read
      contents: write
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    secrets: inherit
    with:
      channel: ${{ matrix.configuration.channel }}
      working-directory: ${{ matrix.configuration.working-directory }}
      tag-prefix: ${{ matrix.configuration.tag-prefix }}
