# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Terraform modules tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/terraform/**'
      - '.github/workflows/test_terraform_modules.yaml'

jobs:
  terraform-tests:
    uses: canonical/operator-workflows/.github/workflows/terraform_modules_test.yaml@main
    secrets: inherit
    with:
      lxd-controller: true
      terraform-directories: '["terraform/dovecot", "terraform/postfix-relay", "dovecot-charm/terraform", "opendkim-operator/terraform", "postfix-relay-operator/terraform", "postfix-relay-configurator-operator/terraform"]'
